services:
  # Combined app and fluent-bit container
  app-fluent:
    build:
      context: .  # Build from root directory to access both demo-app and log-collector
      dockerfile: Dockerfile.combined
    container_name: app-fluent
    volumes:
      # Persistent buffering for fluent-bit
      - ./log-collector/fluent-bit-db:/fluent-bit/db
      - ./log-collector/fluent-bit-storage:/tmp/flb-storage
      - app-logs:/demo-app/src/logs
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - logging_net
    ports:
      - "2020:2020"

  redis:
    image: redis:7-alpine
    container_name: redis-server
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - logging_net

  # bridge:
  #   build:
  #     context: ./bridge
  #   container_name: bridge
  #   depends_on:
  #     - redis
  #   environment:
  #     REDIS_HOST: redis
  #   networks:
  #     - logging_net   
      
  # worker:
  #   build:
  #     context: ./log-parser
  #   container_name: worker
  #   environment:
  #     - REDIS_HOST=redis
  #   volumes:
  #     - ./logs:/app/logs   # To persist the processed_logs.log
  #   depends_on:
  #     - redis
  #   networks:
  #     - logging_net

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "5173:5173"               # Vite dev server default
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules         # Avoids overwriting container's node_modules
  #   command: npm run dev -- --host
  #   depends_on:
  #     - bridge
  #     - worker
  #   networks:
  #     - logging_net

  # backend:
  #   build: ./backend
  #   container_name: backend
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules     # Prevents overwrite of container's node_modules
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - worker
  #   networks:
  #     - logging_net

volumes:
  redis-data:
  app-logs:  # Internal volume for app logs

networks:
  logging_net:
    driver: bridge