
services:

  bridge:
    build:
      context: ./bridge
    container_name: bridge
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    networks:
      - logging_net   
  worker:
    build:
      context: ./log-parser
    container_name: worker
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./logs:/app/logs   # To persist the processed_logs.log
    depends_on:
      - redis
    networks:
      - logging_net


  redis:
    image: redis:7-alpine
    container_name: redis-server
    # ports:
    #   - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - logging_net

  fluent-bit:
    container_name: fluent-bit
    tty: true
    # network_mode: host
    build:
      context: ./log-collector
    volumes:
      # Mount your logs directory - adjust the path as needed
      - ./logs:/logs
      # If your logs are in a different location, use:
      # - /path/to/your/logs:/logs
      - ./log-collector/fluent-bit-db:/fluent-bit/db
      #persistent buffering
      - ./log-collector/fluent-bit-storage:/tmp/flb-storage
      - ./log-collector/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - logging_net
      

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"               # Vite dev server default
    volumes:
      - ./frontend:/app
      - /app/node_modules         # Avoids overwriting container's node_modules
    command: npm run dev -- --host
    depends_on:
      - bridge
      - worker
    networks:
      - logging_net

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules     # Prevents overwrite of container's node_modules
    ports:
      - "3001:3001"
    depends_on:
      - worker
    networks:
      - logging_net

volumes:
  redis-data:

networks:
  logging_net:
    driver: bridge
