services:
  # Combined app and fluent-bit container
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./demo-app/postgres-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - logging_net
    ports:
      - "5432:5432"

  poller:
    build:
      context: .
      dockerfile: log-collector/Dockerfile.combined
    container_name: poller
    env_file:
      - .env
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    command: ["node", "polling-script.js"]
    volumes:
      - app-logs:/demo-app/src/logs
    depends_on:
      - postgres
    networks:
      - logging_net
  
  app-fluent:
    build:
      context: .  # Build from root directory to access both demo-app and log-collector
      dockerfile: log-collector/Dockerfile.combined
    container_name: app-fluent
    volumes:
      # Persistent buffering for fluent-bit
      - ./log-collector/fluent-bit-db:/fluent-bit/db
      - ./log-collector/fluent-bit-storage:/tmp/flb-storage
      - app-logs:/demo-app/src/logs
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    environment:
    - POSTGRES_HOST
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - APP_ID
    restart: unless-stopped
    networks:
      - logging_net
    ports:
      - "2020:2020"

  redis:
    image: redis:7-alpine
    container_name: redis-server
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - logging_net

  bridge:
    build:
      context: ./bridge
    container_name: bridge
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST
    networks:
      - logging_net   
      
  worker:
    build:
      context: ./log-parser
    container_name: worker
    env_file:
      - .env
    environment:
      - REDIS_HOST
      - APP_ID
      - MONGO_URI
    volumes:
      - ./logs:/app/logs   # To persist the processed_logs.log
    depends_on:
      - redis
    networks:
      - logging_net

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "5173:5173"               # Vite dev server default
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules         # Avoids overwriting container's node_modules
  #   command: npm run dev -- --host
  #   depends_on:
  #     - bridge
  #     - worker
  #   networks:
  #     - logging_net

  # backend:
  #   build: ./backend
  #   container_name: backend
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules     # Prevents overwrite of container's node_modules
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - worker
  #   networks:
  #     - logging_net

volumes:
  pgdata:  # Persistent volume for PostgreSQL data
  redis-data:
  app-logs:  # Internal volume for app logs

networks:
  logging_net:
    driver: bridge